import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { pool } from '../../database/pool';
import { AuthContext } from '../../types/public';
import { checkPlannedTeeth, completeExtractions, correctExtraction, readTeeth, writeTeeth } from './dental.service';
import { syncScheduledItems, syncQuoteFromSchedule } from './schedule-dental-sync';
import { scheduleEventSchema } from '../schedule/schedule.schemas';
import { installationCountSql } from '../finance/installation-count';
import { Tooth } from './dental.rules';

test('clinical integration: persistence, stable IDs, audit, tenant isolation, execution and installations',async()=>{
  const client=await pool.connect();
  await client.query('begin');
  try {
    const company=randomUUID(), otherCompany=randomUUID(),user=randomUUID(),patient=randomUUID(),professional=randomUUID(),catalog=randomUUID(),event=randomUUID();
    const auth={empresaId:company,usuarioId:user,perfil:'gestor'} as AuthContext;
    const other={...auth,empresaId:otherCompany};
    await client.query("insert into odonto.empresas(id,nome_fantasia) values($1,'Teste transacional'),($2,'Outra empresa teste')",[company,otherCompany]);
    await client.query("insert into odonto.usuarios(id,nome,login,senha_hash) values($1::uuid,'Teste',$1::uuid::text,'not-a-login')",[user]);
    await client.query("insert into odonto.pacientes(id,empresa_id,nome) values($1,$2,'João Maria Teste')",[patient,company]);
    await client.query("insert into odonto.profissionais(id,empresa_id,nome) values($1,$2,'Profissional Teste')",[professional,company]);
    await client.query("insert into odonto.catalogo_procedimentos(id,empresa_id,nome,valor,duracao_minutos,extracao,forma_cobranca) values($1,$2,'Extração Teste',300,30,true,'POR_DENTE')",[catalog,company]);
    await client.query("insert into odonto.agenda_eventos(id,empresa_id,paciente_id,profissional_id,tipo,titulo,inicio_em,fim_em) values($1,$2,$3,$4,'consulta','Teste','2099-01-05 08:00-03','2099-01-05 09:00-03')",[event,company,patient,professional]);
    const teeth:Tooth[]=[{numero:18,denticao:'permanente'},{numero:28,denticao:'permanente'}];
    const items=scheduleEventSchema.parse({tipo:'consulta',pacienteId:patient,profissionalId:professional,inicioEm:'2099-01-05T08:00:00-03:00',fimEm:'2099-01-05T09:00:00-03:00',procedimentos:[{catalogoProcedimentoId:catalog,quantidade:2,dentes:teeth}]}).procedimentos;
    await syncScheduledItems(client,auth,event,items);
    let row=(await client.query('select * from odonto.agenda_evento_procedimentos where agenda_evento_id=$1',[event])).rows[0];
    assert.equal(Number(row.valor),600);
    assert.deepEqual(await readTeeth(client,auth,'agenda_item_id',row.id),teeth);
    assert.deepEqual(await readTeeth(client,other,'agenda_item_id',row.id),[]);
    const quote=(await client.query("insert into odonto.orcamentos(empresa_id,paciente_id,nome_contato,whatsapp) values($1,$2,'Teste','34999990000') returning id",[company,patient])).rows[0].id;
    await client.query('update odonto.agenda_eventos set orcamento_id=$2 where id=$1',[event,quote]);
    await syncQuoteFromSchedule(client,auth,event,quote,patient);
    row=(await client.query('select * from odonto.agenda_evento_procedimentos where id=$1',[row.id])).rows[0];
    assert.deepEqual(await readTeeth(client,auth,'orcamento_item_id',row.orcamento_item_id),teeth);
    await syncScheduledItems(client,auth,event,[{...items[0],id:row.id}]);
    assert.equal((await client.query('select count(*) from odonto.agenda_evento_procedimentos where agenda_evento_id=$1',[event])).rows[0].count,'1');
    await syncScheduledItems(client,auth,event,[{...items[0],id:row.id,dentes:[teeth[0]],quantidade:1,justificativaDentes:'Execucao parcial programada'}]);
    await syncQuoteFromSchedule(client,auth,event,quote,patient);
    const preserved=(await client.query('select quantidade,valor_total from odonto.orcamento_itens where id=$1',[row.orcamento_item_id])).rows[0];
    assert.equal(preserved.quantidade,2);assert.equal(Number(preserved.valor_total),600);
    await syncScheduledItems(client,auth,event,[{...items[0],id:row.id}]);
    await assert.rejects(()=>checkPlannedTeeth(client,auth,patient,teeth,null));
    await checkPlannedTeeth(client,auth,patient,teeth,null,'Outra abordagem confirmada');
    await assert.rejects(()=>completeExtractions(client,{...auth,perfil:'atendente'},event,[]));
    await assert.rejects(()=>completeExtractions(client,auth,event,[]));
    await assert.rejects(()=>completeExtractions(client,auth,event,[{agendaItemId:row.id,dentes:[teeth[0]],confirmado:true}]));
    await completeExtractions(client,auth,event,[{agendaItemId:row.id,dentes:[teeth[0]],confirmado:true,justificativa:'Segundo dente adiado'}]);
    const realized=(await client.query('select id from odonto.procedimentos_realizados where agenda_item_id=$1',[row.id])).rows[0].id;
    assert.deepEqual(await readTeeth(client,auth,'realizado_id',realized),[teeth[0]]);
    assert.equal(Number((await client.query('select valor from odonto.procedimentos_realizados where id=$1',[realized])).rows[0].valor),300);
    assert.deepEqual(await readTeeth(client,auth,'orcamento_item_id',row.orcamento_item_id),teeth);
    await assert.rejects(()=>syncScheduledItems(client,auth,event,items));
    await correctExtraction(client,auth,realized,teeth,'Correcao documentada do registro');
    assert((await client.query("select count(*) from odonto.audit_logs where empresa_id=$1 and entidade='procedimento_dentes'",[company])).rows[0].count>=4);
    await client.query('savepoint tenant_check');
    await assert.rejects(()=>writeTeeth(client,other,'agenda_item_id',row.id,patient,[{numero:38,denticao:'permanente'}]));
    await client.query('rollback to savepoint tenant_check');
    assert.equal((await client.query("select odonto.search_text('  JOÃO   Maria  ') as term")).rows[0].term,'joao maria');
    // Installation marker, duplicate items, execution date and tenant filters.
    const ortho=randomUUID();
    await client.query("insert into odonto.catalogo_procedimentos(id,empresa_id,nome,valor,tipo_evento_ortodontico) values($1,$2,'Procedimento sem palavra-chave',100,'INSTALACAO')",[ortho,company]);
    await client.query("insert into odonto.agenda_evento_procedimentos(empresa_id,agenda_evento_id,catalogo_procedimento_id,descricao,valor) values($1,$2,$3,'Parte A',100),($1,$2,$3,'Parte B',100)",[company,event,ortho]);
    const count=async(a=auth)=>Number((await client.query(installationCountSql,[a.empresaId,'2099-01-01','2099-01-31'])).rows[0].quantidade);
    assert.equal(await count(),0);
    await client.query("update odonto.agenda_eventos set status='atendido',fim_atendimento_em='2099-01-06 10:00-03' where id=$1",[event]);
    assert.equal(await count(),1);assert.equal(await count(other),0);
    assert.equal(Number((await client.query(installationCountSql,[company,'2099-02-01','2099-02-28'])).rows[0].quantidade),0);
    await client.query("update odonto.agenda_eventos set status='cancelado' where id=$1",[event]);assert.equal(await count(),0);
    await client.query("update odonto.agenda_eventos set status='atendido' where id=$1",[event]);
    await client.query("update odonto.catalogo_procedimentos set tipo_evento_ortodontico='MANUTENCAO' where id=$1",[ortho]);
    assert.equal(await count(),0);
  } finally { await client.query('rollback');client.release();await pool.end(); }
});
